# Generated by Django 3.0.8 on 2020-07-20 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='data_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
